version: '3.8'

services:
  # Frontend Service
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  # Backend Service
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - ml-service

  # ML Service
  ml-service:
    build: ./ml-service
    ports:
      - "8001:8001"
